SELECT 
    P.NAME AS "project",
    SUM(AL.DURATION)::TIME AS "time_spent_by_member",
    ROUND(AVG((EXTRACT(EPOCH FROM (AL.DURATION - AL.IDLE_TIME)) / EXTRACT(EPOCH FROM AL.DURATION))) * 100) AS "average_activity_percentage"
FROM 
    "ACTIVITY_LOG" AL
LEFT JOIN 
    "PROJECT" P ON P.ID = AL.FK_PROJECT
WHERE 
    AL.FK_USER = '39647f9b-a13d-44c9-a5c8-5af01acd526e'
    AND AL.DATE = '2023-05-09'
    AND AL.DELETED_AT IS NULL
GROUP BY 
    P.NAME
ORDER BY 
    P.NAME ASC;